name: infomax
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.12.5
  - certifi=2018.11.29
  - cffi=1.11.5
  - cycler=0.10.0
  - dbus=1.13.2
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.1
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.36
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - sox=14.4.2
  - lz4=2.1.6
  - lz4-c=1.8.1.2
  - matplotlib=3.0.2
  - matplotlib-base=3.0.2
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1a
  - pandas=0.24.0
  - patsy=0.5.1
  - pcre=8.42
  - pillow=5.4.1
  - pip=18.1
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - python=3.6.8
  - python-dateutil=2.7.5
  - pytorch=1.0.0
  - pytz=2018.9
  - qt=5.6.3
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.9.0
  - setuptools=40.6.3
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - torchvision=0.2.1
  - tornado=5.1.1
  - tqdm=4.29.1
  - wget=1.19.5
  - wheel=0.32.3
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:

    - gdown==3.8.3
    - appdirs==1.4.3
    - attrs==19.1.0
    - black==19.3b0
    - click==7.0
    - decorator==4.4.0
    - docopt==0.6.2
    - imageio==2.5.0
    - jsonpickle==0.9.6
    - munch==2.3.2
    - networkx==2.3
    - protobuf==3.7.1
    - py-cpuinfo==5.0.0
    - pywavelets==1.0.3
    - sacred==0.7.4
    - scikit-image==0.15.0
    - tensorboardx==1.6
    - toml==0.10.0
    - torchaudio -f https://download.pytorch.org/whl/torch_stable.html
    - torchviz==0.0.1
    - wrapt==1.11.1
